name: Self Hosted Runner Demo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, amazonlinux, dev]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show system info
        run: |
          echo "Running on self-hosted runner"
          uname -a
          whoami

      - name: Install dependencies (if needed)
        run: |
          sudo yum update -y

      - name: Run a sample script
        run: |
          echo "Hello from EC2 self-hosted runner!"
